export const initialUsers = [
  {
    name: "Admin User",
    email: "admin@example.com",
    password: "admin",
    role: "admin",
    isActive: true,
    avatar: "",
    team: "Staff",
    position: "-",
    height: "0",
    weight: "0",
    birthdate: "01/01/1980",
    phone: "0000000000",
    address: "Oficina",
    nationality: "Argentina",
    statistics: {
      goals: 0,
      assists: 0,
      yellowCards: 0,
      redCards: 0,
      shotsOnTarget: 0,
      matchesPlayed: 0,
      minutesPlayed: 0,
    }
  },
  {
    name: "Lionel Messi",
    email: "messi@example.com",
    password: "leo10",
    role: "player",
    isActive: true,
    avatar: "",
    team: "Inter Miami",
    position: "Delantero",
    height: "170",
    weight: "72",
    birthdate: "24/06/1987",
    phone: "1234567890",
    address: "Rosario",
    nationality: "Argentina",
    statistics: {
      goals: 15,
      assists: 8,
      yellowCards: 1,
      redCards: 0,
      shotsOnTarget: 25,
      matchesPlayed: 10,
      minutesPlayed: 850,
    }
  },  
  {
    name: "Martin Palermo",
    email: "palermo@example.com",
    password: "123456",
    role: "player",
    isActive: true,
    avatar: "",
    team: "Boca jrs",
    position: "Delantero",
    height: "188",
    weight: "85",
    birthdate: "24/06/1985",
    phone: "1234567890",
    address: "BsAs",
    nationality: "Argentina",
    statistics: {
      goals: 200,
      assists: 300,
      yellowCards: 34,
      redCards: 10,
      shotsOnTarget: 28,
      matchesPlayed: 10,
      minutesPlayed: 850,
    }
  }
];
